-- dbeaver 세팅 : 편집기 > SQL 편집기 > SQL 실행 > Parameters

WITH C1 AS (
  SELECT ROWNUM AS RNUM, XX.* FROM
  (
    SELECT
      COLUMN_NAME,
      ', ' || COLUMN_NAME AS HD1,
      ' POSITION(' AS HD2,
      CASE
        WHEN COLUMN_NAME IN (${NOT_INC}) THEN 0
        WHEN DATA_TYPE IN ('NUMBER') AND DATA_PRECISION < DATA_LENGTH AND DATA_SCALE > 0 THEN DATA_PRECISION + 1
        WHEN DATA_TYPE IN ('NUMBER') AND DATA_PRECISION < DATA_LENGTH AND DATA_SCALE = 0 THEN DATA_PRECISION
        WHEN INSTR(DATA_TYPE, 'TIMESTAMP') > 0 THEN 20  -- YYYYMMDDHH24MISSFF6 20, other string : 30
        WHEN INSTR(DATA_TYPE, 'DATE') > 0 THEN 14       -- YYYYMMDDHH24MISS 14, other string : 20
        ELSE DATA_LENGTH
      END AS HD3,
      CASE
        WHEN COLUMN_NAME IN (${NOT_INC}) THEN (
          CASE
            WHEN INSTR(DATA_TYPE, 'DATE') > 0 THEN ' "SYSDATE"'
            WHEN INSTR(DATA_TYPE, 'TIMESTAMP') > 0 THEN ' EXPRESSION "current_timestamp(3)"'
            ELSE ' CONSTANT "system"' -- default mod, inp id
          END
        )
        WHEN INSTR(DATA_TYPE, 'NUMBER') > 0 THEN ' INTEGER EXTERNAL'
        WHEN INSTR(DATA_TYPE, 'TIMESTAMP') > 0 THEN ' TIMESTAMP "YYYYMMDDHH24MISSFF6"'
        ELSE ' CHAR'
      END AS HD4
    FROM ALL_TAB_COLS
    WHERE 1=1
      AND TABLE_NAME = '${TB_NM}'
    ORDER BY COLUMN_ID
  ) XX
)
SELECT AA.HD1 ||
  CASE
    WHEN AA.COLUMN_NAME IN (${NOT_INC}) THEN ''
    ELSE AA.HD2 || (
      CASE
        WHEN AA.RNUM = 1 THEN '1:'
        ELSE ( ( SELECT SUM(HD3) FROM C1 WHERE RNUM <= AA.RNUM ) - HD3 + 1 || ':' )
      END || ( SELECT SUM(HD3) FROM C1 WHERE RNUM <= AA.RNUM ) || ') '
    )
  END ||
  AA.HD4 AS CTL_GEN
  FROM C1 AA
  WHERE 1=1
  ORDER BY AA.RNUM
;
